import type { Strings } from './strings.js'

/** Same rule in English: singular only at exactly one. */
function enCount(count: number, singular: string, plural = `${singular}s`): string {
  return `${count} ${count === 1 ? singular : plural}`
}

export const en: Strings = {
  common: { cancel: 'Cancel', delete: 'Delete', save: 'Save', add: 'Add', type: 'Type', frequency: 'Frequency', expense: 'Expense', income: 'Income', noDescription: '(no description)' },
  appInfo: { description: 'Personal budget management — income, expenses and balance.' },
  format: { frequency: { monthly: 'Monthly', quarterly: 'Quarterly', yearly: 'Yearly' }, recurrenceFrom: (month) => `starting ${month}`, recurrenceRange: (start, end, occurrences) => `${start} → ${end} (${occurrences} times)` },
  remoteStatus: { localStorage: 'Local storage — no server configured', connecting: 'Connecting to the server…', online: 'Connected', onlineSyncedAt: (time) => `Connected — last synced at ${time}`, offline: 'Offline — read-only budget', errorDefault: 'Connection error' },
  icons: { food: 'Food', housing: 'Housing', energy: 'Energy', water: 'Water', heating: 'Heating', diy: 'DIY', transport: 'Transport', travel: 'Travel', commute: 'Commuting', leisure: 'Leisure', games: 'Games', music: 'Music', audio: 'Audio', photo: 'Photo', tv: 'TV', media: 'Media', health: 'Health', sport: 'Sport', insurance: 'Insurance', income: 'Income', expenses: 'Expenses', accounts: 'Accounts', shopping: 'Shopping', spreadsheet: 'Spreadsheet', admin: 'Admin', mail: 'Mail', calendar: 'Calendar', subscriptions: 'Subscriptions', internet: 'Internet', phone: 'Phone', computer: 'Computer', education: 'Education', books: 'Books', family: 'Family', personal: 'Personal', nature: 'Nature', holidays: 'Holidays', favorite: 'Favorite', important: 'Important', other: 'Other' },
  categoriesGroup: { existingCategoriesTitle: 'Existing categories', newCategoryTitle: 'New category', nameFieldTitle: 'Name', addTooltip: 'Add', iconTooltip: (iconLabel) => `Icon: ${iconLabel} — click to change`, alreadyExists: (name) => `The category "${name}" already exists`, added: 'Category added', iconChanged: 'Icon changed', renamed: 'Category renamed', deleteTooltip: 'Delete this category', mustKeepOne: 'At least one category must remain', deleteBody: 'Transactions already recorded keep this category: ' + 'only the list offered when entering one changes.', deleted: 'Category deleted' },
  categoryCombo: { title: 'Category' },
  cloudGroup: { serverGroupTitle: 'WebDAV server', serverGroupDescription: 'The budget is read from and written to the server; the local files are only ' + 'a cache. Without a network, the budget stays readable but can no longer be edited. ' + 'Compatible with Nextcloud, ownCloud and any WebDAV server.', addressLabel: 'Server address', addressTooltip: (hint) => `For example ${hint}`, usernameLabel: 'Username', passwordLabel: 'Password', directoryLabel: 'Remote folder', useServerLabel: 'Use the server', useServerSubtitle: 'When off, the budget stays on this machine', statusGroupTitle: 'Status', syncButton: 'Sync', connectButton: 'Connect', forgetButton: 'Forget', passwordKeptSubtitle: 'Kept in the system keyring, never in the budget files', missingAddress: 'Enter the server address and username', keyringUnavailable: 'Keyring unavailable — set BUDGET_APP_REMOTE_PASSWORD', noPasswordSaved: 'No password saved for this account', disconnected: 'Server disconnected — the budget stays on this machine' },
  confirmDeleteDialog: { heading: (name) => `Delete "${name}"?` },
  editScopeDialog: { heading: 'Recurring transaction', bodyOccurrence: 'Apply the change to this occurrence only, or to the whole series?', bodySeriesOnly: 'The frequency can only be changed for the whole series: ' + 'upcoming months will follow the new rhythm.', occurrenceOption: 'This occurrence', seriesOption: 'Whole series' },
  dataGroup: { operationFailed: 'Operation failed', exportBackupTitle: 'Export a backup', importBackupTitle: 'Import a backup', exportCsvTitle: 'Export the transactions', importCsvTitle: 'Import transactions', backupExported: (description) => `Backup exported — ${description}`, noTransactionsToExport: 'No transactions to export', backupGroupTitle: 'Full backup', backupGroupDescription: 'A JSON file containing the categories, the thresholds, ' + 'the recurrences and the whole history of months.', exportBackupSubtitle: 'Save the current state to a file', exportButton: 'Export…', importBackupSubtitle: 'Restore a file, replacing or merging', importButton: 'Import…', csvGroupTitle: 'Spreadsheet (CSV)', csvGroupDescription: 'Date, description, category, type and amount columns, ' + 'separated by semicolons — readable in Excel or LibreOffice.', exportCsvSubtitle: 'Every month, oldest to newest', importCsvSubtitle: 'Each row joins the month of its date and is added to the existing transactions', backupFilterName: 'Budget backup', csvFilterName: 'CSV file', monthsCount: (count) => enCount(count, 'month'), transactionsCount: (count) => enCount(count, 'transaction'), categoriesCount: (count) => enCount(count, 'category', 'categories'), recurrencesCount: (count) => enCount(count, 'recurrence'), transactionsExportedCount: (count) => `${enCount(count, 'transaction')} exported`, transactionsImportedCount: (count) => `${enCount(count, 'transaction')} imported`, categoriesCreatedCount: (count) => `${enCount(count, 'category', 'categories')} created`, linesIgnoredCount: (count) => `${enCount(count, 'line')} ignored`, restored: (description) => `Backup restored — ${description}`, nothingToAdd: 'Nothing to add: this data is already present', mergeCompleted: (parts) => `Merge complete — added ${parts}`, csvImportSummary: (imported, monthsLabel) => `${imported} across ${monthsLabel}` },
  importModeDialog: { heading: 'Import the backup', body: (summary) => `This backup contains ${summary}.\n\n` + 'Merging only adds what is missing and keeps the current data. ' + 'Replacing erases the current data — months, categories, thresholds and recurrences — ' + 'in favour of the file\'s.', mergeOption: 'Merge', replaceOption: 'Replace' },
  iconPickerDialog: { title: 'Choose an icon' },
  occurrenceCountField: { limitedTitle: 'Limited length', limitedSubtitle: 'Otherwise the series repeats forever', countTitle: 'Number of occurrences' },
  generalSettings: {
    groupTitle: 'General preferences', groupDescription: 'Choose the language, formats and application theme.',
    languageTitle: 'Language', languageFrench: 'Français', languageEnglish: 'English', currencyTitle: 'Currency',
    dateFormatTitle: 'Date format', dateLocale: 'According to language', amountFormatTitle: 'Amount format',
    amountLocale: 'According to language', themeTitle: 'Theme', themeSystem: 'System', themeLight: 'Light', themeDark: 'Dark',
    saveButton: 'Save', saved: 'Preferences saved',
  },
  optionsDialog: { title: 'Options', generalTab: 'General', thresholdsTab: 'Thresholds', recurrencesTab: 'Recurrences', categoriesTab: 'Categories', dataTab: 'Data', cloudTab: 'Cloud' },
  recurrenceDialog: { defaultDescription: (kind) => (kind === 'income' ? 'Recurring income' : 'Recurring expense'), transactionGroupTitle: 'Generated transaction', typeRow: 'Type', descriptionLabel: 'Description', amountLabel: 'Amount (€)', rhythmGroupTitle: 'Rhythm', rhythmGroupDescription: 'The transaction is created automatically when each concerned month opens.', dayLabel: 'Day of the month', daySubtitle: 'Clamped to the last day of shorter months', startMonthLabel: 'Starting month', startYearLabel: 'Starting year', startYearSubtitle: 'No occurrence before this month', editTitle: 'Edit the recurrence', newTitle: 'New recurrence' },
  recurrencesGroup: { groupTitle: 'Recurring transactions', groupDescription: 'Each recurrence is automatically added to the months it concerns, ' + 'as soon as they open.', dayPrefix: (day) => `day ${day}`, editTooltip: 'Edit this recurrence', deleteTooltip: 'Delete this recurrence', updated: 'Recurrence updated', deleteBody: 'Transactions already added to opened months are kept: ' + 'only the upcoming ones will no longer be created.', deleted: 'Recurrence deleted — transactions already created are kept', addTooltip: 'Add a recurrence', added: 'Recurrence added', emptyTitle: 'No recurrence', emptySubtitle: 'Rent, salary, subscription… add one with the + button' },
  thresholdsGroup: { groupTitle: 'Balance thresholds', groupDescription: (rule) => 'Balance background colour: red below x, orange from x to y, ' + `yellow from y to z, green from z onward. The thresholds must respect ${rule}.`, lowLabel: 'Red threshold', mediumLabel: 'Orange threshold', highLabel: 'Yellow threshold', orderError: (rule) => `The thresholds must respect ${rule}`, saved: 'Thresholds saved', saveButton: 'Save' },
  transactionDialog: { defaultDescription: (kind) => (kind === 'income' ? 'Income' : 'Expense'), typeRow: 'Type', amountLabel: 'Amount (€)', onceLabel: 'One-off', repeatGroupTitle: 'Repetition', repeatGroupDescription: 'A repeated transaction is recreated automatically, on the same day, ' + 'in every concerned month, as soon as it opens.', editTitle: 'Edit the transaction', newTitle: 'New transaction' },
  budgetView: { edited: 'Transaction updated', editedRecurring: 'Transaction updated and made recurring', occurrenceEdited: 'Occurrence updated — the recurrence is unchanged', recurrenceRemoved: 'Recurrence removed — the transaction becomes one-off', recurrenceUpdated: 'Recurrence updated', deleteBodyOccurrence: (details) => `${details}\n\nThis transaction comes from a recurrence: it will reappear ` + 'the next time the month opens. To stop it from being created, ' + 'delete the recurrence in the options instead.', deleteBodyOnce: (details) => `${details}\n\nIt will be removed from the month for good.`, occurrenceDeleted: 'Occurrence deleted — it will reappear the next time the month opens', deleted: 'Transaction deleted', tabRecurring: 'Recurring', tabOther: 'Other', tabCharts: 'Charts' },
  categoryCharts: { recurringExpenseTitle: 'Recurring expenses by category', otherExpenseTitle: 'Other expenses by category', noData: 'No data', legendTooltip: 'Show legend', sliceDetails: (category, amount, percent) => `${category}: ${amount} (${percent})` },
  listTotal: { total: 'Total', countLabel: (shown, monthCount) => (shown === monthCount ? enCount(shown, 'transaction') : `${enCount(shown, 'transaction')} out of ${monthCount}`) },
  monthSwitcher: { previousMonth: 'Previous month', nextMonth: 'Next month', pickMonth: 'Pick a month', previousYear: 'Previous year', nextYear: 'Next year', goToCurrentMonth: 'Go to current month', monthWithData: (month) => `${month} — has transactions` },
  summaryCards: { balance: 'Balance', income: 'Income', expenses: 'Expenses' },
  transactionFilters: { kindAll: 'All', kindIncome: 'Income', kindExpense: 'Expenses', anyCategory: 'All', searchPlaceholder: 'Search a description or category…', kindTooltip: 'Show only one transaction type', categoryTooltip: 'Show only some categories', resetTooltip: 'Reset the filters', categoriesCount: (count) => enCount(count, 'category', 'categories') },
  transactionList: { recurringTitle: 'Recurring transactions', otherTitle: 'Other transactions', emptyTitle: 'No transactions', emptyDescription: 'Click "+" to add an income or an expense to this month.', noMatchTitle: 'No results', noMatchDescription: 'This month has transactions, but none match the filter.' },
  transactionRow: { dayLabel: 'Day', dayValue: (day) => `the ${day} of the month`, periodLabel: 'Period', occurrenceLabel: 'This occurrence', defaultDescription: 'Recurring transaction', editTooltip: 'Edit this transaction', deleteTooltip: 'Delete this transaction' },
  mainWindow: { optionsMenu: 'Options', aboutMenu: (appName) => `About ${appName}`, quitMenu: 'Quit', addTransactionTooltip: 'Add a transaction', added: 'Transaction added', addedRecurring: 'Recurring transaction added', retryButton: 'Retry', serverUnreachable: 'Server unreachable — read-only budget', historyMenu: 'History', budgetMenu: 'Budget' },
  historyView: { title: 'Monthly history', description: 'Income and expenses month by month.', income: 'Income', expenses: 'Expenses', noData: 'No history data' },
}
