/*
 * domain/transaction.ts — the transaction model and the pure rules that
 * operate on it (validation, sorting, aggregation). No GTK, no I/O: this
 * module is the single source of truth for *what* a budget is, independent
 * of how it is stored or displayed.
 */

export type TransactionKind = 'income' | 'expense'

export interface Transaction {
  id: string
  /** ISO date string, e.g. "2026-09-17". */
  date: string
  description: string
  category: string
  kind: TransactionKind
  /** Always positive; the sign is derived from `kind`. */
  amount: number
  /** Set when the transaction was generated by a recurrence — see domain/recurrence.ts. */
  recurrenceId?: string
}

/** A transaction that has not been persisted yet (no id assigned). */
export type TransactionInput = Omit<Transaction, 'id'>

export interface Totals {
  income: number
  expense: number
  balance: number
}

function isTransaction(value: unknown): value is Transaction {
  if (typeof value !== 'object' || value === null) return false
  const candidate = value as Partial<Transaction>
  return (
    typeof candidate.id === 'string' &&
    typeof candidate.date === 'string' &&
    typeof candidate.description === 'string' &&
    typeof candidate.category === 'string' &&
    (candidate.kind === 'income' || candidate.kind === 'expense') &&
    typeof candidate.amount === 'number' &&
    Number.isFinite(candidate.amount) &&
    (candidate.recurrenceId === undefined || typeof candidate.recurrenceId === 'string')
  )
}

/** Type guard used when reading `transactions.json`: rejects anything malformed. */
export function isTransactionArray(value: unknown): value is Transaction[] {
  return Array.isArray(value) && value.every(isTransaction)
}

/** Most recent transactions first. Returns a new array; the input is untouched. */
export function sortByDateDesc(transactions: readonly Transaction[]): Transaction[] {
  return [...transactions].sort((a, b) => b.date.localeCompare(a.date))
}

export function computeTotals(transactions: readonly Transaction[]): Totals {
  let income = 0
  let expense = 0
  for (const transaction of transactions) {
    if (transaction.kind === 'income') income += transaction.amount
    else expense += transaction.amount
  }
  return { income, expense, balance: income - expense }
}

export interface CategoryTotal {
  category: string
  amount: number
}

/** Total amount per category for a given kind, largest first. */
export function sumByCategory(
  transactions: readonly Transaction[],
  kind: TransactionKind,
): CategoryTotal[] {
  const totals = new Map<string, number>()
  for (const transaction of transactions) {
    if (transaction.kind !== kind) continue
    totals.set(transaction.category, (totals.get(transaction.category) ?? 0) + transaction.amount)
  }
  return [...totals.entries()]
    .map(([category, amount]) => ({ category, amount }))
    .sort((a, b) => b.amount - a.amount)
}

/** Today as an ISO date string ("YYYY-MM-DD"), the default date of a new transaction. */
export function todayIsoDate(): string {
  return new Date().toISOString().slice(0, 10)
}
